// client/React-TodoList/src/Layout/Error.tsx
import React from "react";
import { useOvermind } from "../Overmind";

const Error: React.FC = () => {
  const {
    state: {
      auth: { error },
    },
  } = useOvermind();
  return (
    <div
      className={`fixed bottom-0 w-full h-16 bg-red-500 text-white transition-transform transform ${
        error !== null ? " " : "translate-y-16"
      } duration-200 ease-in-out`}
    >
      <div className="flex flex-row items-center justify-center text-3xl text-center max-w-full h-full">
        {error as string}
      </div>
    </div>
  );
};

export default Error;

// client/Svelte-TodoList/src/Layout/Error.svelte
<script>
  import { fly } from "svelte/transition";
  import { quintOut } from "svelte/easing";
  import { error } from "../stores/error.js";
</script>

{#if $error !== null}
  <div
    class="fixed bottom-0 w-full h-16 bg-red-700 text-white flex flex-row
    items-center justify-center text-3xl"
    transition:fly={{ duration: 300, x: 0, y: -50, easing: quintOut }}>
    {$error}
  </div>
{/if}
