// client/React-TodoList/src/Layout/Sidebar.tsx
import React, { Fragment } from "react";
import { useOvermind } from "../Overmind/index";
import { useHistory } from "react-router-dom";

interface Props {
  isOpen: boolean;
  setIsOpen: Function;
}

const Sidebar: React.FC<Props> = (props) => {
  const { isOpen, setIsOpen } = props;
  const {
    state: {
      darkMode: { isEnabled },
      auth: { isAuthenticated },
    },
    actions: {
      darkMode: { turnOff, turnOn },
      auth: { logout },
    },
  } = useOvermind();

  const history = useHistory();

  return (
    <Fragment>
      <div
        className={`fixed flex flex-col items-center left-0 top-0 h-full w-48 bg-white dark:bg-dark-gray-800 dark:text-white shadow py-4 transform transition-transform ${
          isOpen ? "" : "-translate-x-48"
        } duration-300 ease-in-out z-10`}
      >
        <button
          className="flex items-center justify-center py-4 w-full hover:bg-white-alpha-30 focus:outline-none transition-colors duration-300
    ease-in-out px-2 border-b-2 border-gray-700 dark:border-gray-400"
          onClick={() => (isEnabled ? turnOff() : turnOn())}
        >
          <i className="material-icons">
            {isEnabled ? "brightness_7" : "brightness_4"}
          </i>
        </button>
        <a
          className="flex items-center justify-center py-4 w-full hover:bg-white-alpha-30 focus:outline-none transition-colors duration-300
          ease-in-out px-2 border-b-2 border-gray-700 dark:border-gray-400"
          href="/"
        >
          Pick A Framework
        </a>
        {isAuthenticated ? (
          <button
            className="flex items-center justify-center py-4 w-full hover:bg-white-alpha-30 focus:outline-none transition-colors duration-300
    ease-in-out px-2 border-b-2 border-gray-700 dark:border-gray-400"
            onClick={() => {
              logout();
              setIsOpen(false);
            }}
          >
            Logout
          </button>
        ) : (
          <Fragment>
            <button
              className="flex items-center justify-center py-4 w-full dark:text-white hover:bg-white-alpha-30 focus:outline-none transition-colors duration-300
    ease-in-out px-2 border-b-2 border-gray-700 dark:border-gray-400"
              onClick={() => {
                history.push("/");
                setIsOpen(false);
              }}
            >
              Login
            </button>
            <button
              className="flex items-center justify-center py-4 w-full dark:text-white hover:bg-white-alpha-30 focus:outline-none transition-colors duration-300
    ease-in-out px-2 border-b-2 border-gray-700 dark:border-gray-400"
              onClick={() => {
                history.push("/register");
                setIsOpen(false);
              }}
            >
              Register
            </button>
          </Fragment>
        )}
      </div>
      <button
        className={`fixed left-0 right-0 top-0 bottom-0 ${
          isOpen ? "bg-black-alpha-50  h-full w-full" : ""
        } transition-colors duration-300 ease-in-out`}
        onClick={() => setIsOpen(false)}
      />
    </Fragment>
  );
};

export default Sidebar;

// client/Svelte-TodoList/src/Layout/Sidebar.svelte
<script>
  import { fade, fly } from "svelte/transition";
  import { quintOut } from "svelte/easing";
  import { darkMode } from "../stores/darkMode.js";
  import { auth } from "../stores/auth.js";
  import { push } from "svelte-spa-router";

  const { turnOff, turnOn } = darkMode;
  const { Logout } = auth;

  export let isOpen;
</script>

{#if isOpen}
  <div
    transition:fly={{ duration: 300, x: -192, easing: quintOut }}
    class="fixed flex flex-col items-center h-full top-0 left-0 w-48 bg-white
    dark:bg-dark-gray-700 z-10 shadow">
    <button
      on:click={() => {
        $darkMode ? turnOff() : turnOn();
      }}
      class="w-full py-8 focus:outline-none dark:text-white border-b-2
      border-gray-700 dark:border-gray-400">
      {#if $darkMode}
        <i class="material-icons flex items-center justify-center">
          brightness_7
        </i>
      {:else}
        <i class="material-icons flex items-center justify-center">
          brightness_4
        </i>
      {/if}
    </button>
    <a
      class="w-full text-center py-4 focus:outline-none dark:text-white
      border-b-2 transition-colors duration-300 ease-in-out border-gray-700
      dark:border-gray-400 hover:bg-white-alpha-30"
      href="/">
      Pick A Framework
    </a>
    {#if $auth}
      <button
        class="w-full py-4 focus:outline-none dark:text-white border-b-2
        transition-colors duration-300 ease-in-out border-gray-700
        dark:border-gray-400 hover:bg-white-alpha-30"
        on:click={() => {
          Logout();
          isOpen = false;
        }}>
        Logout
      </button>
    {:else}
      <button
        class="w-full py-4 focus:outline-none dark:text-white border-b-2
        border-gray-700 dark:border-gray-400 hover:bg-white-alpha-30
        transition-colors duration-300 ease-in-out"
        on:click={() => {
          push('/');
          isOpen = false;
        }}>
        Login
      </button>
      <button
        class="w-full py-4 focus:outline-none dark:text-white border-b-2
        border-gray-700 dark:border-gray-400 hover:bg-white-alpha-30
        transition-colors duration-300 ease-in-out"
        on:click={() => {
          push('/register');
          isOpen = false;
        }}>
        Register
      </button>
    {/if}
  </div>
  <button
    transition:fade={{ duration: 300, easing: quintOut }}
    class="fixed left-0 right-0 top-0 bottom-0 h-full w-full bg-black-alpha-50
    focus:outline-none"
    on:click={() => (isOpen = false)} />
{/if}
