// client/Svelte-TodoList/src/Components/NewTodo.svelte
<script>
  import { todos } from "../stores/todos.js";
  let todo = {};
</script>

<div
  class="flex flex-col w-full bg-gray-300 dark:bg-gray-700 mx-auto mt-24 p-4
  shadow max-w-screen-md mb-8 rounded">
  <div class="text-center text-4xl dark:text-white font-hairline mb-4">
    New Todo
  </div>
  <input
    class="border-b-2 border-black text-black dark:text-white dark:border-white
    bg-transparent focus:border-deep-orange-a400 mb-4 p-2 transition-colors
    duration-300 ease-in-out focus:outline-none placeholder-gray-700
    dark-placeholder:placeholder-gray-300"
    type="text"
    placeholder="Title"
    name="title"
    bind:value={todo.title} />
  <textarea
    class="border-b-2 border-black dark:text-white text-black dark:border-white
    bg-transparent focus:border-deep-orange-a400 mb-4 p-2 transition-colors
    duration-300 ease-in-out focus:outline-none placeholder-gray-700
    dark-placeholder:placeholder-gray-300"
    type="text"
    placeholder="Description"
    name="description"
    bind:value={todo.description} />
  <button
    on:click={() => todos.NewTodo(todo)}
    class="bg-light-blue-400 py-2 rounded shadow focus:outline-none">
    Add
  </button>
</div>

// client/React-TodoList/src/Components/NewTodo.tsx
import React from "react";

const NewTodo: React.FC = () => {
  interface NewTodo {
    title: string | null;
    description: string | null;
  }

  const newTodo: NewTodo = {
    title: null,
    description: null,
  };

  return (
    <div className="flex flex-col w-90p mx-auto p-4 max-w-screen-sm mt-24 bg-gray-400 dark:bg-gray-800 rounded shadow text-black dark:text-white">
      <div className="text-center  text-4xl font-hairline mb-4">New Todo</div>
      <input
        className="border-b-2 border-black dark:border-white bg-transparent 
      focus:border-light-blue-300 mb-4 p-2 transition-colors
      duration-300 ease-in-out focus:outline-none placeholder-gray-700
      dark-placeholder:placeholder-gray-300"
        type="text"
        placeholder="Title"
        name="title"
        onChange={(e) => (newTodo.title = e.target.value as string)}
      />
      <input
        className="border-b-2 border-black dark:border-white bg-transparent
      focus:border-light-blue-300 mb-4 p-2 transition-colors
      duration-300 ease-in-out focus:outline-none placeholder-gray-700
      dark-placeholder:placeholder-gray-300"
        type="text"
        placeholder="Description"
        name="description"
        onChange={(e) => (newTodo.description = e.target.value as string)}
      />
      <button
        className="bg-light-blue-300 py-2 rounded shadow focus:outline-none"
        onClick={() => {}}
      >
        Add
      </button>
    </div>
  );
};

export default NewTodo;
