// client/Vue-TodoList/src/components/NewTodo.vue
<template>
  <div
    class="flex flex-col mx-auto mt-24 bg-gray-900 dark:bg-gray-300 w-90p max-w-screen-sm p-4 rounded shadow"
  >
    <div class="text-white dark:text-black text-4xl font-hairline text-center mb-4">New Todo</div>
    <input
      class="text-white dark:text-black bg-transparent border-b-2 dark:border-gray-800 focus:border-vue-green-500 focus:outline-none transition-colors duration-300 ease-in-out dark-placeholder:placeholder-gray-800 p-2 mb-4"
      type="text"
      placeholder="Title"
      name="title"
      v-model="newTodoData.title"
    />
    <input
      class="text-white dark:text-black bg-transparent border-b-2 dark:border-gray-800 focus:border-vue-green-500 focus:outline-none transition-colors duration-300 ease-in-out dark-placeholder:placeholder-gray-800 p-2 mb-4"
      type="text"
      placeholder="Description"
      name="description"
      v-model="newTodoData.description"
    />
    <button
      class="w-full p-2 bg-vue-green-500 rounded shadow focus:outline-none"
      v-on:click="newTodo(newTodoData)"
    >Add</button>
  </div>
</template>

<script>
import { mapActions } from "vuex";

export default {
  name: "NewTodo",
  methods: {
    ...mapActions(["newTodo"]),
    handleAddNewTodo: function() {
      this.newTodo(this.newTodoData);
    }
  },
  data: () => {
    return {
      newTodoData: {}
    };
  }
};
</script>

// client/React-TodoList/src/Components/NewTodo.tsx
import React from "react";

const NewTodo: React.FC = () => {
  interface NewTodo {
    title: string | null;
    description: string | null;
  }

  const newTodo: NewTodo = {
    title: null,
    description: null,
  };

  return (
    <div className="flex flex-col w-90p mx-auto p-4 max-w-screen-sm mt-24 bg-gray-400 dark:bg-gray-800 rounded shadow text-black dark:text-white">
      <div className="text-center  text-4xl font-hairline mb-4">New Todo</div>
      <input
        className="border-b-2 border-black dark:border-white bg-transparent 
      focus:border-light-blue-300 mb-4 p-2 transition-colors
      duration-300 ease-in-out focus:outline-none placeholder-gray-700
      dark-placeholder:placeholder-gray-300"
        type="text"
        placeholder="Title"
        name="title"
        onChange={(e) => (newTodo.title = e.target.value as string)}
      />
      <input
        className="border-b-2 border-black dark:border-white bg-transparent
      focus:border-light-blue-300 mb-4 p-2 transition-colors
      duration-300 ease-in-out focus:outline-none placeholder-gray-700
      dark-placeholder:placeholder-gray-300"
        type="text"
        placeholder="Description"
        name="description"
        onChange={(e) => (newTodo.description = e.target.value as string)}
      />
      <button
        className="bg-light-blue-300 py-2 rounded shadow focus:outline-none"
        onClick={() => {}}
      >
        Add
      </button>
    </div>
  );
};

export default NewTodo;
