// client/Vue-TodoList/src/components/Todo.vue
<template>
  <div
    class="flex flex-row items-center justify-center w-full border-2 border-gray-300 dark:border-gray-800 p-2 m-1"
  >
    <input
      class="mx-4"
      type="checkbox"
      v-model="todo.done"
      v-on:change="handleChecked()"
    />
    <div class="w-full">
      <div>{{ todo.title }}</div>
      <small>{{ todo.description }} {{ ` - ${month}/${day}` }}</small>
    </div>
    <button
      class="flex mx-4 focus:outline-none"
      v-on:click="deleteTodo(todo._id)"
    >
      <i class="material-icons text-red-800">clear</i>
    </button>
  </div>
</template>

<script>
import { mapActions } from "vuex";

export default {
  props: ["todo"],
  data: () => {
    return {
      day: null,
      month: null,
    };
  },
  methods: {
    ...mapActions(["updateTodo", "deleteTodo"]),
    handleChecked() {
      this.updateTodo({
        body: { isDone: this.todo.isDone },
        id: this.todo._id,
      });
    },
  },
  mounted: function() {
    const date = new Date(this.todo.createdAt * 1000);
    const dateTimeFormat = new Intl.DateTimeFormat("en", {
      month: "short",
      day: "2-digit",
    });
    const [{ value: month }, , { value: day }] = dateTimeFormat.formatToParts(
      date
    );

    this.day = day;
    this.month = month;
  },
};
</script>

// client/React-TodoList/src/Components/Todo.tsx
import React from "react";
import { useOvermind } from "../Overmind";
import { UpdateTodoArg } from "../Overmind/todos/actions";
import { Todo } from "../Overmind/todos/state";

interface TodoProps {
  todo: Todo;
  key: number;
}

const TodoComp: React.FC<TodoProps> = (props) => {
  const { todo } = props;

  const {
    actions: {
      todos: { updateTodo, deleteTodo },
    },
  } = useOvermind();

  const date = new Date(todo.createdAt * 1000);
  const dateTimeFormat = new Intl.DateTimeFormat("en", {
    month: "short",
    day: "2-digit",
  });
  const [{ value: month }, , { value: day }] = dateTimeFormat.formatToParts(
    date
  );

  // changeIsDone.body.isdone CANNOT be camelcase because ShouldBindJSON in this route does not respect case
  let changeIsDone: UpdateTodoArg = {
    id: todo._id,
    body: {
      done: !todo.done,
    },
  };

  return (
    <div className="flex flex-row items-center h-full w-full border border-black dark:border-white p-2 m-1">
      <input
        className="mx-4"
        type="checkbox"
        checked={todo.done}
        onChange={() => updateTodo(changeIsDone)}
      />
      <div className="h-full w-full">
        <div>{todo.title}</div>
        <small>
          {todo.description} {` - ${month}/${day}`}
        </small>
      </div>
      <button
        className="flex h-full mx-2 focus:outline-none"
        onClick={() => deleteTodo(todo._id)}
      >
        <i className="material-icons text-red-800">clear</i>
      </button>
    </div>
  );
};

export default TodoComp;
