// client/Vue-TodoList/src/pages/Login.vue
<template>
  <div>
    <div
      class="flex flex-col mx-auto mt-24 bg-gray-900 dark:bg-gray-300 w-90p max-w-screen-sm p-4 rounded shadow"
    >
      <div
        class="text-white dark:text-black text-4xl font-hairline text-center mb-4"
      >
        Login
      </div>
      <input
        class="text-white dark:text-black bg-transparent border-b-2 dark:border-gray-800 focus:border-vue-green-500 focus:outline-none transition-colors duration-300 ease-in-out dark-placeholder:placeholder-gray-800 p-2 mb-4"
        type="text"
        placeholder="Email"
        name="email"
        v-model="cred.email"
      />
      <input
        class="text-white dark:text-black bg-transparent border-b-2 dark:border-gray-800 focus:border-vue-green-500 focus:outline-none transition-colors duration-300 ease-in-out dark-placeholder:placeholder-gray-800 p-2 mb-4"
        type="text"
        placeholder="Password"
        name="password"
        v-model="cred.password"
      />
      <button
        class="w-full p-2 bg-vue-green-500 rounded shadow focus:outline-none"
        v-on:click="handleLogin"
      >
        Login
      </button>
    </div>
    <div class="flex flex-col items-center justify-center w-full mt-4">
      <div class="mb-2 text-black dark:text-white">or</div>
      <button
        class="bg-vue-green-500 py-2 px-4 rounded shadow"
        v-on:click="handleDemoLogin"
      >
        use the Demo account
      </button>
    </div>
  </div>
</template>

<script>
import { mapActions, mapState } from "vuex";
export default {
  name: "Login",
  methods: {
    ...mapActions(["login", "getMe"]),
    handleLogin: function() {
      this.login(this.cred);
    },
    handleDemoLogin: function() {
      this.login({
        email: "Demo@gmail.com",
        password: "123456",
      });
    },
  },
  data: () => {
    return {
      cred: {},
    };
  },
  computed: mapState({
    isAuthenticated: (state) => state.auth.isAuthenticated,
  }),
  mounted: function() {
    if (this.isAuthenticated) {
      this.$router.push("/todos");
    } else {
      this.getMe();
    }
  },
};
</script>

// client/Svelte-TodoList/src/Pages/Login.svelte
<script>
  import { auth } from "../stores/auth.js";
  import { onMount } from "svelte";

  onMount(() => {
    auth.GetMe();
  });

  let cred = {
    email: "",
    password: ""
  };
</script>

<section>
  <div
    class="flex flex-col w-90p bg-gray-300 dark:bg-gray-700 mx-auto mt-24 p-4
    rounded shadow max-w-screen-sm">
    <div
      class="text-center text-4xl text-black dark:text-white font-hairline mb-4">
      Login
    </div>
    <input
      class="border-b-2 border-black dark:border-white bg-transparent
      focus:border-deep-orange-a400 text-black dark:text-white mb-4 p-2
      transition-colors duration-300 ease-in-out focus:outline-none
      placeholder-gray-700 dark-placeholder:placeholder-gray-300"
      type="text"
      placeholder="Email"
      name="email"
      bind:value={cred.email} />
    <input
      class="border-b-2 border-black dark:border-white bg-transparent
      focus:border-deep-orange-a400 text-black dark:text-white mb-4 p-2
      transition-colors duration-300 ease-in-out focus:outline-none
      placeholder-gray-700 dark-placeholder:placeholder-gray-300"
      type="text"
      placeholder="Password"
      name="password"
      bind:value={cred.password} />
    <button
      on:click={() => auth.Login(cred)}
      class="bg-light-blue-400 py-2 rounded shadow focus:outline-none">
      Submit
    </button>
  </div>
  <div
    class="flex flex-col items-center justify-center w-full text-black
    dark:text-white mt-4">
    <div class="mb-2">or</div>
    <button
      class="bg-deep-orange-a400 text-black rounded shadow py-2 px-4"
      on:click={() => auth.Login({
          email: 'Demo@gmail.com',
          password: '123456'
        })}>
      use the Demo account
    </button>
  </div>
</section>
