// client/Vue-TodoList/src/pages/Todos.vue
<template>
  <div>
    <NewTodo />
    <div
      class="flex flex-col items-center justify-center bg-gray-900 dark:bg-gray-300 text-white dark:text-black mt-24 w-90p mx-auto max-w-screen-sm p-4 rounded shadow"
    >
      <Todo v-for="todo in todos" v-bind:key="todo._id" v-bind:todo="todo" />
    </div>
  </div>
</template>

<script>
import { mapState, mapActions } from "vuex";
import NewTodo from "../components/NewTodo.vue";
import Todo from "../components/Todo.vue";

export default {
  name: "Todos",
  components: {
    Todo,
    NewTodo
  },
  methods: {
    ...mapActions(["getTodos"])
  },
  computed: mapState({
    todos: state => state.todosState.todos,
    isAuthenticated: state => state.auth.isAuthenticated
  }),
  mounted: function() {
    if (this.isAuthenticated) {
      this.getTodos();
    } else {
      this.$router.push("/");
    }
  }
};
</script>

// client/Svelte-TodoList/src/Pages/Todos.svelte
<script>
  import Todo from "../Components/Todo.svelte";
  import NewTodo from "../Components/NewTodo.svelte";
  import { flip } from "svelte/animate";
  import { todos } from "../stores/todos.js";
  import { onMount } from "svelte";
  import { auth } from "../stores/auth.js";
  import { push } from "svelte-spa-router";

  onMount(() => {
    if ($auth === false) {
      push("/");
      return;
    }
    todos.GetTodos();
  });
</script>

<section>
  <div
    class="flex flex-col items-center justify-center mx-auto w-90p
    max-w-screen-md">
    <NewTodo />
    <div class="bg-gray-300 dark:bg-gray-700 w-full p-4 rounded shadow">
      {#each $todos as todo (todo._id)}
        <div class="w-full" animate:flip={{ duration: 500 }}>
          <Todo {todo} />
        </div>
      {/each}
    </div>

  </div>
</section>
