// client/Vue-TodoList/src/pages/CreateUser.vue
<template>
  <div
    class="flex flex-col mx-auto mt-24 bg-gray-900 dark:bg-gray-300 w-90p max-w-screen-sm p-4 rounded shadow"
  >
    <div class="text-white dark:text-black text-4xl font-hairline text-center mb-4">Register</div>
    <input
      class="text-white dark:text-black bg-transparent border-b-2 dark:border-gray-800 focus:border-vue-green-500 focus:outline-none transition-colors duration-300 ease-in-out dark-placeholder:placeholder-gray-800 p-2 mb-4"
      type="text"
      placeholder="Name"
      name="name"
      v-model="cred.name"
    />
    <input
      class="text-white dark:text-black bg-transparent border-b-2 dark:border-gray-800 focus:border-vue-green-500 focus:outline-none transition-colors duration-300 ease-in-out dark-placeholder:placeholder-gray-800 p-2 mb-4"
      type="text"
      placeholder="Email"
      name="email"
      v-model="cred.email"
    />
    <input
      class="text-white dark:text-black bg-transparent border-b-2 dark:border-gray-800 focus:border-vue-green-500 focus:outline-none transition-colors duration-300 ease-in-out dark-placeholder:placeholder-gray-800 p-2 mb-4"
      type="text"
      placeholder="Password"
      name="password"
      v-model="cred.password"
    />
    <button
      class="w-full p-2 bg-vue-green-500 rounded shadow focus:outline-none"
      v-on:click="handleRegister()"
    >Register</button>
  </div>
</template>

<script>
import { mapActions, mapState } from "vuex";
export default {
  name: "Login",
  methods: {
    ...mapActions(["createUser", "getMe"]),
    handleRegister: function() {
      this.createUser(this.cred);
    }
  },
  data: () => {
    return {
      cred: {}
    };
  },
  computed: mapState({
    isAuthenticated: state => state.auth.isAuthenticated
  }),
  mounted: function() {
    if (this.isAuthenticated) {
      this.$router.push("/todos");
    } else {
      this.getMe();
    }
  }
};
</script>

// client/React-TodoList/src/Pages/CreateUser.tsx
import React, { useEffect, useState } from "react";
import { useOvermind } from "../Overmind";
import { useHistory } from "react-router-dom";

const CreateUser: React.FC = () => {
  const [newUser, setNewUser] = useState<NewUser>({
    name: null,
    email: null,
    password: null,
  });

  const {
    state: {
      auth: { isAuthenticated },
    },
    actions: {
      auth: { createUser },
    },
  } = useOvermind();

  const history = useHistory();

  interface NewUser {
    name: string | null;
    email: string | null;
    password: string | null;
  }

  useEffect(() => {
    if (isAuthenticated) history.push("/todos");
  }, [isAuthenticated, history]);

  return (
    <div className="flex flex-col w-90p mx-auto p-4 max-w-screen-sm mt-24 bg-gray-400 dark:bg-gray-800 rounded shadow text-black dark:text-white">
      <div className="text-center  text-4xl font-hairline mb-4">
        New Account
      </div>
      <input
        className="border-b-2 border-black dark:border-white bg-transparent 
      focus:border-light-blue-300 mb-4 p-2 transition-colors
      duration-300 ease-in-out focus:outline-none placeholder-gray-700
      dark-placeholder:placeholder-gray-300"
        type="text"
        placeholder="Name"
        name="name"
        onChange={(e) => setNewUser({ ...newUser, name: e.target.value })}
      />
      <input
        className="border-b-2 border-black dark:border-white bg-transparent 
      focus:border-light-blue-300 mb-4 p-2 transition-colors
      duration-300 ease-in-out focus:outline-none placeholder-gray-700
      dark-placeholder:placeholder-gray-300"
        type="text"
        placeholder="Email"
        name="email"
        onChange={(e) => setNewUser({ ...newUser, email: e.target.value })}
      />
      <input
        className="border-b-2 border-black dark:border-white bg-transparent
      focus:border-light-blue-300 mb-4 p-2 transition-colors
      duration-300 ease-in-out focus:outline-none placeholder-gray-700
      dark-placeholder:placeholder-gray-300"
        type="text"
        placeholder="Password"
        name="password"
        onChange={(e) => setNewUser({ ...newUser, password: e.target.value })}
      />
      <button
        className="bg-light-blue-300 py-2 rounded shadow focus:outline-none"
        onClick={() => {
          createUser(newUser);
        }}
      >
        Register
      </button>
    </div>
  );
};

export default CreateUser;
