// client/Vue-TodoList/src/pages/Todos.vue
<template>
  <div>
    <NewTodo />
    <div
      class="flex flex-col items-center justify-center bg-gray-900 dark:bg-gray-300 text-white dark:text-black mt-24 w-90p mx-auto max-w-screen-sm p-4 rounded shadow"
    >
      <Todo v-for="todo in todos" v-bind:key="todo._id" v-bind:todo="todo" />
    </div>
  </div>
</template>

<script>
import { mapState, mapActions } from "vuex";
import NewTodo from "../components/NewTodo.vue";
import Todo from "../components/Todo.vue";

export default {
  name: "Todos",
  components: {
    Todo,
    NewTodo
  },
  methods: {
    ...mapActions(["getTodos"])
  },
  computed: mapState({
    todos: state => state.todosState.todos,
    isAuthenticated: state => state.auth.isAuthenticated
  }),
  mounted: function() {
    if (this.isAuthenticated) {
      this.getTodos();
    } else {
      this.$router.push("/");
    }
  }
};
</script>

// client/React-TodoList/src/Pages/Todos.tsx
import React, { useEffect } from "react";
import { useOvermind } from "../Overmind";
import { useHistory } from "react-router-dom";

import NewTodo from "../Components/NewTodo";
import Todo from "../Components/Todo";

const Todos: React.FC = () => {
  const {
    state: {
      auth: { isAuthenticated },
      todos: { todos },
    },
    actions: {
      todos: { getTodos },
    },
  } = useOvermind();

  const history = useHistory();

  let allTodos = todos.map((todo, index) => (
    <Todo todo={todo as Todo} key={index} />
  ));

  useEffect(() => {
    if (!isAuthenticated) history.push("/");

    getTodos();

    //eslint-disable-next-line
  }, [isAuthenticated]);

  return (
    <section>
      <NewTodo />
      <div className="flex flex-col w-90p mx-auto p-4 max-w-screen-sm mt-24 bg-gray-400 dark:bg-gray-800 rounded shadow text-black dark:text-white">
        {allTodos}
      </div>
    </section>
  );
};

export default Todos;
