// client/React-TodoList/src/App.tsx
import React from "react";
import { BrowserRouter as Router, Route, Switch } from "react-router-dom";
import { Provider } from "overmind-react";
import { createOvermind } from "overmind";
import { config } from "./Overmind";
import "./css/tailwind.css";

import Navbar from "./Layout/Navbar";
import Login from "./Pages/Login";
import Todos from "./Pages/Todos";
import CreateUser from "./Pages/CreateUser";
import Error from "./Layout/Error";

const App: React.FC = () => {
  const overmind = createOvermind(config, {
    devtools: true,
  });

  return (
    <Provider value={overmind}>
      <Router>
        <Navbar />
        <Switch>
          <Route exact path="/" component={Login} />
          <Route exact path="/todos" component={Todos} />
          <Route exact path="/register" component={CreateUser} />
        </Switch>
        <Error />
      </Router>
    </Provider>
  );
};

export default App;

// client/Svelte-TodoList/src/App.svelte
<script>
  import Navbar from "./Layout/Navbar.svelte";
  import Login from "./Pages/Login.svelte";
  import Todos from "./Pages/Todos.svelte";
  import Router from "svelte-spa-router";
  import Error from "./Layout/Error.svelte";
  import NewUser from "./Pages/NewUser.svelte";

  import "./CSS/tailwind.css";

  import { media } from "./stores/watchMedia.js";
  import { darkMode } from "./stores/darkMode.js";

  if ($media.dark) {
    darkMode.turnOn();
  }

  const routes = {
    "/": Login,
    "/register": NewUser,
    "/todos": Todos
  };
</script>

<Navbar />
<Router {routes} />
<Error />
