// client/Vue-TodoList/src/layout/Error.vue
<template>
  <div
    class="fixed bottom-0 flex items-center justify-center bg-red-500 text-white text-2xl w-full h-16 transition-transform transform duration-200 ease-in-out"
    v-bind:class="{ 'translate-y-16': !authError }"
  >{{ authError }}</div>
</template>

<script>
import { mapState } from "vuex";
export default {
  name: "Error",
  computed: mapState({
    authError: state => state.auth.error
  })
};
</script>

// client/React-TodoList/src/Layout/Error.tsx
import React from "react";
import { useOvermind } from "../Overmind";

const Error: React.FC = () => {
  const {
    state: {
      auth: { error },
    },
  } = useOvermind();
  return (
    <div
      className={`fixed bottom-0 w-full h-16 bg-red-500 text-white transition-transform transform ${
        error !== null ? " " : "translate-y-16"
      } duration-200 ease-in-out`}
    >
      <div className="flex flex-row items-center justify-center text-3xl text-center max-w-full h-full">
        {error as string}
      </div>
    </div>
  );
};

export default Error;
