// client/Vue-TodoList/src/layout/Navbar.vue
<template>
  <div class="w-full h-16 bg-vue-green-400 shadow">
    <div
      class="flex flex-row items-center justify-between w-90p mx-auto h-full"
    >
      <div
        class="flex items-center justify-center h-full text-3xl font-hairline"
      >
        TodoList
      </div>
      <div class="flex flex-row h-full">
        <Fragment v-if="$mq === 'sm'">
          <button
            class="flex h-full px-2 hover:bg-white-alpha-30 transition-colors duration-300 ease-in-out focus:outline-none"
          >
            <i class="material-icons">menu</i>
          </button>
        </Fragment>
        <Fragment v-else>
          <button
            v-if="isAuthenticated"
            v-on:click="logout"
            class="flex h-full px-2 hover:bg-white-alpha-30 transition-colors duration-300 ease-in-out focus:outline-none"
          >
            Logout
          </button>
          <button
            v-if="darkMode"
            v-on:click="turnOff"
            class="flex h-full px-2 hover:bg-white-alpha-30 transition-colors duration-300 ease-in-out focus:outline-none"
          >
            <i class="material-icons">brightness_7</i>
          </button>
          <button
            v-else
            v-on:click="turnOn"
            class="flex h-full px-2 hover:bg-white-alpha-30 transition-colors duration-300 ease-in-out focus:outline-none"
          >
            <i class="material-icons">brightness_4</i>
          </button>
        </Fragment>
      </div>
    </div>
  </div>
</template>

<script>
import { Fragment } from "vue-fragment";
import { mapState, mapActions } from "vuex";

export default {
  name: "Navbar",
  components: {
    Fragment,
  },
  methods: {
    ...mapActions(["turnOn", "turnOff", "logout"]),
  },
  computed: mapState({
    darkMode: (state) => state.darkMode.darkMode,
    isAuthenticated: (state) => state.auth.isAuthenticated,
  }),
};
</script>

// client/React-TodoList/src/Layout/Navbar.tsx
import React, { Fragment } from "react";
import { useMediaQuery } from "react-responsive";
import { useOvermind } from "../Overmind/index";

const Navbar: React.FC = () => {
  const {
    state: {
      darkMode: { isEnabled },
      auth: { isAuthenticated },
    },
    actions: {
      darkMode: { turnOff, turnOn },
      auth: { logout },
    },
  } = useOvermind();

  let isDesktop: boolean = useMediaQuery({ query: "(min-width: 1024px)" });

  const desktopNav = (
    <Fragment>
      {isAuthenticated ? (
        <Fragment>
          <button
            className="h-full hover:bg-white-alpha-30 transition-colors duration-300 ease-in-out focus:outline-none px-2"
            onClick={() => logout()}
          >
            Logout
          </button>
          <button
            className="flex h-full hover:bg-white-alpha-30 focus:outline-none transition-colors duration-300
    ease-in-out px-2"
            onClick={() => (isEnabled ? turnOff() : turnOn())}
          >
            <i className="material-icons">
              {isEnabled ? "brightness_7" : "brightness_4"}
            </i>
          </button>
        </Fragment>
      ) : (
        <button
          className="flex h-full hover:bg-white-alpha-30 focus:outline-none transition-colors duration-300
    ease-in-out px-2"
          onClick={() => (isEnabled ? turnOff() : turnOn())}
        >
          <i className="material-icons">
            {isEnabled ? "brightness_7" : "brightness_4"}
          </i>
        </button>
      )}
    </Fragment>
  );

  const mobile = (
    <button
      className="h-full hover:bg-white-alpha-30 transition-colors duration-300
    ease-in-out px-2"
    >
      <i className="material-icons">menu</i>
    </button>
  );

  return (
    <div className="w-full h-16 bg-light-blue-300">
      <div className="flex flex-row justify-between w-90p h-full mx-auto">
        <div className="flex items-center text-2xl font-hairline h-full">
          TodoList
        </div>
        <div className="flex flex-row items-center justify-center h-full">
          {isDesktop ? desktopNav : mobile}
        </div>
      </div>
    </div>
  );
};

export default Navbar;
