// client/Vue-TodoList/src/layout/Sidebar.vue
<template>
  <div>
    <div
      class="fixed flex flex-col items-center left-0 top-0 bottom-0 h-full w-48 bg-white dark:bg-dark-gray-800 transform z-10 transition-transform transform duration-300 ease-in-out shadow"
      v-bind:class="{ '-translate-x-48': !isOpen }"
    >
      <button
        v-on:click="toggleDarkMode"
        class="flex items-center justify-center w-full h-16 focus:outline-none border-b-2 border-gray-300 dark:border-gray-600"
      >
        <i v-if="darkMode" class="material-icons text-white">brightness_7</i>
        <i v-else class="material-icons">brightness_4</i>
      </button>
      <a
        class="dark:text-white w-full hover:bg-black-alpha-20 transition-colors duration-300 ease-in-out py-4 text-center focus:outline-none border-b-2 border-gray-300 dark:border-gray-600"
        href="/"
        >Pick A Framework</a
      >
      <button
        v-if="isAuthenticated"
        v-on:click="handleLogout"
        class="dark:text-white w-full hover:bg-black-alpha-20 transition-colors duration-300 ease-in-out py-4 focus:outline-none border-b-2 border-gray-300 dark:border-gray-600"
      >
        Logout
      </button>
      <button
        v-if="!isAuthenticated"
        v-on:click="pushLogin"
        class="dark:text-white w-full hover:bg-black-alpha-20 transition-colors duration-300 ease-in-out py-4 focus:outline-none border-b-2 border-gray-300 dark:border-gray-600"
      >
        Login
      </button>
      <button
        v-if="!isAuthenticated"
        v-on:click="pushRegister"
        class="dark:text-white w-full hover:bg-black-alpha-20 transition-colors duration-300 ease-in-out py-4 focus:outline-none border-b-2 border-gray-300 dark:border-gray-600"
      >
        Register
      </button>
    </div>
    <button
      class="fixed left-0 right-0 top-0 bottom-0 transition-colors duration-300 ease-in-out focus:outline-none"
      v-bind:class="{ 'bg-black-alpha-50 h-full w-full': isOpen }"
      v-on:click="toggleIsOpen"
    />
  </div>
</template>

<script>
import { mapState, mapActions } from "vuex";
export default {
  name: "Sidebar",
  props: ["isOpen", "toggleIsOpen"],
  methods: {
    ...mapActions(["turnOn", "turnOff", "logout"]),
    toggleDarkMode() {
      this.darkMode ? this.turnOff() : this.turnOn();
    },
    handleLogout() {
      this.logout(), this.toggleIsOpen();
    },
    pushLogin() {
      if (this.$router.currentRoute.path !== "/") this.$router.push("/");
      this.toggleIsOpen();
    },
    pushRegister() {
      if (this.$router.currentRoute.path !== "/register")
        this.$router.push("/register");
      this.toggleIsOpen();
    },
  },
  computed: mapState({
    darkMode: (state) => state.darkMode.darkMode,
    isAuthenticated: (state) => state.auth.isAuthenticated,
  }),
};
</script>

// client/React-TodoList/src/Layout/Sidebar.tsx
import React, { Fragment } from "react";
import { useOvermind } from "../Overmind/index";
import { useHistory } from "react-router-dom";

interface Props {
  isOpen: boolean;
  setIsOpen: Function;
}

const Sidebar: React.FC<Props> = (props) => {
  const { isOpen, setIsOpen } = props;
  const {
    state: {
      darkMode: { isEnabled },
      auth: { isAuthenticated },
    },
    actions: {
      darkMode: { turnOff, turnOn },
      auth: { logout },
    },
  } = useOvermind();

  const history = useHistory();

  return (
    <Fragment>
      <div
        className={`fixed flex flex-col items-center left-0 top-0 h-full w-48 bg-white dark:bg-dark-gray-800 dark:text-white shadow py-4 transform transition-transform ${
          isOpen ? "" : "-translate-x-48"
        } duration-300 ease-in-out z-10`}
      >
        <button
          className="flex items-center justify-center py-4 w-full hover:bg-white-alpha-30 focus:outline-none transition-colors duration-300
    ease-in-out px-2 border-b-2 border-gray-700 dark:border-gray-400"
          onClick={() => (isEnabled ? turnOff() : turnOn())}
        >
          <i className="material-icons">
            {isEnabled ? "brightness_7" : "brightness_4"}
          </i>
        </button>
        <a
          className="flex items-center justify-center py-4 w-full hover:bg-white-alpha-30 focus:outline-none transition-colors duration-300
          ease-in-out px-2 border-b-2 border-gray-700 dark:border-gray-400"
          href="/"
        >
          Pick A Framework
        </a>
        {isAuthenticated ? (
          <button
            className="flex items-center justify-center py-4 w-full hover:bg-white-alpha-30 focus:outline-none transition-colors duration-300
    ease-in-out px-2 border-b-2 border-gray-700 dark:border-gray-400"
            onClick={() => {
              logout();
              setIsOpen(false);
            }}
          >
            Logout
          </button>
        ) : (
          <Fragment>
            <button
              className="flex items-center justify-center py-4 w-full dark:text-white hover:bg-white-alpha-30 focus:outline-none transition-colors duration-300
    ease-in-out px-2 border-b-2 border-gray-700 dark:border-gray-400"
              onClick={() => {
                history.push("/");
                setIsOpen(false);
              }}
            >
              Login
            </button>
            <button
              className="flex items-center justify-center py-4 w-full dark:text-white hover:bg-white-alpha-30 focus:outline-none transition-colors duration-300
    ease-in-out px-2 border-b-2 border-gray-700 dark:border-gray-400"
              onClick={() => {
                history.push("/register");
                setIsOpen(false);
              }}
            >
              Register
            </button>
          </Fragment>
        )}
      </div>
      <button
        className={`fixed left-0 right-0 top-0 bottom-0 ${
          isOpen ? "bg-black-alpha-50  h-full w-full" : ""
        } transition-colors duration-300 ease-in-out`}
        onClick={() => setIsOpen(false)}
      />
    </Fragment>
  );
};

export default Sidebar;
